name: codebooter_study_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'  # Updated for Flutter 3.x compatibility

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  cupertino_icons: ^1.0.5
  go_router: ^12.0.0
  url_strategy: ^0.2.0
  animated_splash_screen: ^1.3.0
  
  # Updated Firebase packages
  firebase_core: ^2.24.1
  google_sign_in: ^6.1.5
  github_sign_in_plus: ^0.0.1
  firebase_auth: ^4.12.1
  firebase_auth_oauth: ^1.1.0
  
  flutter_highlight: ^0.7.0
  mongo_dart: ^0.9.1
  http: ^0.13.6
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  liquid_progress_indicator: ^0.4.0
  
  youtube_player_flutter: ^8.1.2
  youtube_data_api: ^1.0.4
  intl: ^0.18.1
  syncfusion_flutter_pdfviewer: ^21.2.10
  path_provider: ^2.1.1
  cached_network_image: ^3.3.0
  dio: ^5.3.2
  carousel_slider: ^4.2.1
  flutter_blurhash: ^0.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/logo1.png